# Generated by Django 2.2.26 on 2022-01-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evangelisation', '0004_auto_20220108_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evangelisation',
            name='boss',
            field=models.ManyToManyField(blank=True, related_name='participations', to='evangelisation.Participant', verbose_name='Qui sont présents ?'),
        ),
        migrations.AlterField(
            model_name='person',
            name='boss',
            field=models.ManyToManyField(blank=True, help_text='selectionner les personnes ayant évangelisés cette personne', related_name='personnes', to='evangelisation.Participant', verbose_name="Qui l'ont évangelisé ?"),
        ),
        migrations.AlterField(
            model_name='person',
            name='contacts',
            field=models.PositiveIntegerField(blank=True, error_messages={'unique': 'Une personne avec ce numéro de télephone existe déjà'}, null=True, unique=True, verbose_name='Numéro de téléphone'),
        ),
    ]
