# Generated by Django 2.2.26 on 2022-01-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evangelisation', '0005_auto_20220116_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contacts',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numéro de téléphone'),
        ),
    ]
