# Generated by Django 2.2.26 on 2022-01-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evangelisation', '0007_auto_20220116_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contacts',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Le numéro de téléphone doit avoir 09 chiffres', null=True, verbose_name='Numéro de téléphone'),
        ),
    ]
