# Generated by Django 2.2.26 on 2022-01-21 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evangelisation', '0008_auto_20220116_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_personnes', to=settings.AUTH_USER_MODEL, verbose_name='Enrgistré par '),
        ),
        migrations.AlterField(
            model_name='person',
            name='evangelisation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='personnes', to='evangelisation.Evangelisation', verbose_name="Moment d'évangelisation"),
        ),
    ]
