# Generated by Django 2.2.26 on 2022-01-21 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evangelisation', '0009_auto_20220121_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='evangelisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='personnes', to='evangelisation.Evangelisation', verbose_name="Moment d'évangelisation"),
        ),
        migrations.AlterField(
            model_name='person',
            name='nom_et_prenom',
            field=models.CharField(error_messages={'unique': 'Une personne avec ce nom existe déjà'}, help_text='ce champ doit avoir au moins trois caractères', max_length=200, null=True, unique=True, verbose_name='Nom et Prénom'),
        ),
    ]
