# Generated by Django 2.2.26 on 2022-01-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evangelisation', '0011_auto_20220121_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('-nom_et_prenom',), 'verbose_name': 'Personne évangélisé'},
        ),
        migrations.AlterField(
            model_name='person',
            name='contacts',
            field=models.PositiveIntegerField(blank=True, default='---', help_text='Le numéro de téléphone doit avoir 09 chiffres', null=True, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='person',
            name='quartier_d_habitation',
            field=models.CharField(blank=True, default='---', help_text='ce champ doit avoir au moins trois caractères', max_length=200, null=True, verbose_name="Quartier d'habitation"),
        ),
    ]
