# Generated by Django 2.2.26 on 2022-01-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evangelisation', '0012_auto_20220121_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='images_root/logo/vh-yde.jpg', help_text='ajouter une photo', null=True, upload_to='images/profile/%Y/'),
        ),
    ]
